% 作业内容：线性调频信号的IQ路以及频谱

%参数
f0=1e10;
Tp=1e-5;
B=1e7;
fs=1e8;
R0=3e3;
c=3e8;
tau=2*R0/c;
k=B/Tp;
%回波信号模型
t=tau-Tp/2:1/fs:tau+Tp/2;
s=exp(1j*pi*k.*(t-tau).^2)*exp(-1j*2*pi*f0*tau);
t_out=-Tp/2:1/fs:Tp/2;
s_out=exp(1j*pi*k.*t_out.^2);
figure;
subplot(2,1,1);
plot(t,real(s));
xlabel("时间/s");
ylabel("幅度")
title("线性调频信号回波");
%脉冲压缩滤波器形式
%滤波后结果
ts=ifftshift(ifft(conj(fft(s_out)).*fft(s)));
tt=tau-Tp/2:1/fs:tau+Tp/2;
subplot(2,1,2);
plot(tt,ts);
xlabel("时间/s");
ylabel("幅度")
title("匹配滤波结果")

%I、Q路波形
I=real(s);
Q=imag(s);
x=t*c;
figure;
subplot(4,1,1);
plot(x,I);
xlabel("距离/m");
ylabel("幅度")
title("I路信号")
subplot(4,1,2);
plot(x,Q);
xlabel("距离/m");
ylabel("幅度")
title("Q路信号")


I_fft=fftshift(fft(I));
Q_fft=fftshift(fft(Q));
fv=-fs/2:fs/1000:fs/2;
subplot(4,1,3);
plot(fv,I_fft);
xlabel("频率/Hz");
ylabel("幅度")
title("I路信号频谱")
subplot(4,1,4)
plot(fv,Q_fft);
xlabel("频率/Hz");
ylabel("幅度")
title("Q路信号频谱")
%参考信号波形
figure;
subplot(4,1,1);
plot(x,I);
xlabel("距离/m");
ylabel("幅度")
title("参考信号I路信号")
subplot(4,1,2);
plot(x,Q);
xlabel("频率/Hz");
ylabel("幅度")
title("参考信号Q路信号")
subplot(4,1,3);
plot(fv,I_fft);
xlabel("频率/Hz");
ylabel("幅度")
title("参考信号I路信号频谱")
subplot(4,1,4)
plot(fv,Q_fft);
xlabel("距离/m");
ylabel("幅度")
title("参考信号Q路信号")
%脉冲压缩后时域波形
figure;
tsdB = db(abs(ts)/max(abs(ts)));
plot(tt,tsdB);
xlabel("距离/m");
ylabel("幅度(dB)")
title("脉冲压缩后信号")